export const FETCH_COVIDSTATS_PENDING = 'FETCH_COVIDSTATS_PENDING';
export const FETCH_COVIDSTATS_SUCCESS = 'FETCH_COVIDSTATS_SUCCESS';
export const FETCH_COVIDSTATS_ERROR = 'FETCH_COVIDSTATS_ERROR';
export const TRANSLATE_COVIDSTATS_COUNTRY_NAME = 'TRANSLATE_COVIDSTATS_COUNTRY_NAME';  
export const GET_SPECIFIC_COUNTRY_STATS = 'GET_SPECIFIC_COUNTRY_STATS'; 